name: Build SO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r28

      - name: Build
        run: ndk-build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: libs/
